### ISSUE TITLE
Disable left blue hot corner

### ISSUE THREAD

**Issue by wesbluemarine** [helloSystem/KWin#8]
The left hot corner is really annoyng when you need to click "Search".
Can be solved with this line on **kwinrc** under **[Effect-PresentWindows]** section:

`BorderActivateAll=9`

**Comment by probonopd** [comment]
`/usr/local/etc/xdg/kwinrc`

Hot corners:

```
7 - 0 - 1
6 -   - 2
5 - 4 - 3
```

`9`: Disable

For example:

```
[Effect-DesktopGrid]
BorderActivate=9

[Effect-PresentWindows]                
BorderActivateAll=9
BorderActivate=9
```

**Comment by probonopd** [comment]
Deactivated in favor of new menu item with shortcut in Menu.

**Comment by louies0623** [comment]
It has not been fixed in the latest development preview version. When restarting kwin_x11.app, the problem will appear again.
![20230924_125841](https://github.com/helloSystem/KWin/assets/44593430/d593dbf7-2c09-46e4-b4e8-bd520cacf734)

**Comment by probonopd** [comment]
In that screenshot KWin isnt running properly: There are no window decorations, and there are menus in the windows instead of in the global menu.
Also, please always mention the concrete build, not "latest". Guessing that you mean 0I44. Thanks!

I cannot reproduce this issue. What do you mean by "restarting kwin_x11.app"? There is only `KWin.app`, but users normally should not need to restart it.

**Comment by louies0623** [comment]
1. Open the System file window, 2. Then open the program manager, 3. Then force close kwin-x11.app and menu.app, 4. Then open the System file window kwin-x11.app and menu.app The problem reappears

**Comment by probonopd** [comment]
That's hopefully not something our users should ever have to do :-)
